//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration.Toolkit.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Migration.Toolkit.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment moved to media library, media file path: ({0}/{1}).
        /// </summary>
        public static string Attachment_MovedToLibrary {
            get {
                return ResourceManager.GetString("Attachment_MovedToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped attachment moved to media library, media file path: ({0}/{1}).
        /// </summary>
        public static string AttachmentGrouped_ModevToLibrary {
            get {
                return ResourceManager.GetString("AttachmentGrouped_ModevToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Configuration error{1}: {2}.
        /// </summary>
        public static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}Possible fix{1}: {2}.
        /// </summary>
        public static string ConfigurationRecommendedFix {
            get {
                return ResourceManager.GetString("ConfigurationRecommendedFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path  &apos;Settings.XbKApiSettings.ConnectionStrings.CMSConnectionString&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_CmsConnectionString_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_CmsConnectionString_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Settings.XbKApiSettings.ConnectionStrings&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_ConnectionStrings_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_ConnectionStrings_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Settings&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_Settings_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_Settings_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path &apos;Settings.KxCmsDirPath&apos; is empty, it is recommended to set source instance filesystem path.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_SourceCmsDirPath_IsRecommended {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_SourceCmsDirPath_IsRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path &apos;Settings.KxConnectionString&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_SourceConnectionString_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_SourceConnectionString_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path &apos;Settings.XbKDirPath&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_TargetCmsDirPath_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_TargetCmsDirPath_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path &apos;Settings.XbKConnectionString&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_TargetConnectionString_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_TargetConnectionString_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Settings.XbKApiSettings&apos; is required.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_TargetKxpApiSettings_IsRequired {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_TargetKxpApiSettings_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path &apos;Settings.UseOmActivityNodeRelationAutofix&apos; must fit one of: {0}.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_UseOmActivityNodeRelationAutofix_MustFit {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_UseOmActivityNodeRelationAutofix_MustF" +
                        "it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value in path &apos;Settings.UseOmActivitySiteRelationAutofix&apos; must fit one of: {0}.
        /// </summary>
        public static string ConfigurationValidator_GetValidationErrors_UseOmActivitySiteRelationAutofix_MustFit {
            get {
                return ResourceManager.GetString("ConfigurationValidator_GetValidationErrors_UseOmActivitySiteRelationAutofix_MustF" +
                        "it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Configuration warning{1}: {2}.
        /// </summary>
        public static string ConfigurationWarning {
            get {
                return ResourceManager.GetString("ConfigurationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document relationship is currently not supported - related to: {0}.
        /// </summary>
        public static string Document_Relationship_NotSupported {
            get {
                return ResourceManager.GetString("Document_Relationship_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ExplicitPrimaryKeyMapping of {1} is required..
        /// </summary>
        public static string Exception_MappingIsRequired {
            get {
                return ResourceManager.GetString("Exception_MappingIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit program....
        /// </summary>
        public static string ProgramAwaitingExitMessage {
            get {
                return ResourceManager.GetString("ProgramAwaitingExitMessage", resourceCulture);
            }
        }
    }
}
